export const LISTAR_PRODUCTOS = "LISTAR_PRODUCTOS";
export const LISTAR_PRODUCTOS_ERROR = "LISTAR_PRODUCTOS_ERROR"
 
export const MOSTRAR_PRODUCTO = "MOSTRAR_PRODUCTO"
export const MOSTRAR_PRODUCTO_ERROR = "MOSTRAR_PRODUCTO_ERROR";
